version: '3.8'

services:
  test:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    command: npm test

  dev:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run test:watch